artifact_uri: remote_server_uri/1/bbaded54d160423197affffcdf88efe4/artifacts
end_time: 1644128508980
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bbaded54d160423197affffcdf88efe4
run_uuid: bbaded54d160423197affffcdf88efe4
source_name: ''
source_type: 4
source_version: ''
start_time: 1644128508961
status: 4
tags: []
user_id: shubham
